version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: dom-postgres
    restart: unless-stopped
    env_file: .env.db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4:9.7.0
    container_name: dom-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  api:
    build: .
    container_name: dom-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    # Para desenvolvimento com auto-reload, descomente as duas linhas abaixo:
    # volumes:
    #   - ./:/app

volumes:
  pgdata:
  pgadmin_data:
